### ISSUE TITLE
功能样式建议：pin样式可以标识吗？

### ISSUE THREAD

**Issue by luluciamk** [TCOTC/siyuan-css-pin-doc-show#1]
大大，关于pin住的文档可以增加一个pin标志吗？？
如图
![image](https://github.com/user-attachments/assets/de41162e-d16f-456e-ae43-43a6eb03ca30)
修改成类似积读的这种
![image](https://github.com/user-attachments/assets/3e2e3bf1-979e-4b67-bcdc-dad63098c54f)
加了标志后信息更加明确。

**Comment by TCOTC** [comment]
你可以试试用这个代码片段：

```css
#layouts .layout__center div:not(.fn__none) > .layout-tab-bar:not(.layout-tab-bar--readonly) .item--pin::before {
    content: "📌";
    font-size: 0.8em;
    position: absolute;
    right: 0;
    bottom: 0;
}
```

![image](https://github.com/user-attachments/assets/a9068c72-b086-476a-9da1-edad5af39a6a)
